cmake/configs/default.cmake, cmake/projects/HastyNoise/hunter.cmake
* https://ci.appveyor.com/project/caseymcc/hunter
* https://travis-ci.org/caseymcc/hunter/builds/579621262
=> Add HastyNoise v0.8.3

cmake/projects/SPIRV-Headers/hunter.cmake
* https://ci.appveyor.com/project/mchiasson/hunter/builds/27804633
* https://travis-ci.org/mchiasson/hunter/builds/592180149
---
=> Improved 'SPIRV-Headers' build time

cmake/configs/default.cmake, cmake/projects/spirv-cross/hunter.cmake
* https://ci.appveyor.com/project/mchiasson/hunter-testing/builds/28027284
* https://travis-ci.com/mchiasson/hunter-testing/builds/131383740
=> Update 'spirv-cross' to 20190906

cmake/configs/default.cmake, cmake/projects/Lua/hunter.cmake
* https://ci.appveyor.com/project/caseymcc/hunter/builds/27904964
* https://travis-ci.org/caseymcc/hunter/builds/594016178
=> Update to lua 5.3.5

cmake/configs/default.cmake, cmake/projects/GTest/hunter.cmake, examples/GTest/CMakeLists.txt
=> Update GTest to 1.8.1

cmake/configs/default.cmake, cmake/projects/GTest/hunter.cmake
* https://ci.appveyor.com/project/rbsheth/hunter/builds/28537203
* https://travis-ci.com/rbsheth/hunter/builds/134511160
* This update will break few old toolchains.
They are excluded in this pull request: https://github.com/cpp-pm/hunter-testing/pull/15
=> Update 'GTest' to v1.10.0

cmake/configs/default.cmake, cmake/projects/Protobuf/hunter.cmake
* I've tested this package remotely and have excluded all broken builds. [Yes]
=> Update 'Protobuf' to v3.10.0-p0

cmake/configs/default.cmake, cmake/projects/spdlog/hunter.cmake
Upstream commit for spdlog v1.4.2-p0 from https://github.com/ruslo/hunter
Closes #57
=> Update spdlog to v1.4.2

cmake/configs/default.cmake, cmake/projects/Catch/hunter.cmake
* https://ci.appveyor.com/project/kaihowl/hunter/builds/28920829
* https://travis-ci.com/kaihowl/hunter/builds/136892836
=> Update Catch to 2.11.0

.github/ISSUE_TEMPLATE.md, .github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/discussion.md
* I've checked this [CMake style guide](https://0.readthedocs.io/en/latest/cmake.html). **Not applicable**
* My change will work with CMake 3.2 (minimum requirement for Hunter). **Not applicable**
* I will try to keep this pull request as small as possible and will try not to mix unrelated features. **YES**
=> Update code of conduct link to new fork

cmake/projects/ZLIB/hunter.cmake
#74 didn't do exactly what I wanted, in that chromium_zlib wasn't downloaded properly nor was the ALIAS target correctly set up. Should be fixed in this PR.
=> Fix chromium_zlib as ZLIB

cmake/configs/default.cmake, cmake/projects/sqlite3/hunter.cmake
* https://ci.appveyor.com/project/kaihowl/hunter/builds/29166881
* https://travis-ci.com/kaihowl/hunter/builds/138470086
Fixes #70
=> Update sqlite3 to 3.30.1

cmake/configs/default.cmake, cmake/projects/BZip2/hunter.cmake
Closes #83 
* https://ci.appveyor.com/project/rbsheth/hunter/builds/29321382
* https://travis-ci.com/rbsheth/hunter/builds/139424105
FYI @Bjoe
=> Update 'BZip2' to v1.0.8-p0

README.rst
appveyor links are not working
other ingenue links updated to point to cpp-pm/hunter-testing
=> Update ingenue links in README.rst

cmake/projects/Qt/hunter.cmake
=> Fix Qt URLs

docs/reference/user-modules/hunter_source_subdir.rst
Copy paste error for the usage example of hunter_source_subdir()
=> docs: fix hunter_source_subdir example usage

cmake/configs/default.cmake, cmake/projects/zstd/hunter.cmake, docs/packages/pkg/zstd.rst, examples/zstd/CMakeLists.txt, examples/zstd/foo.c
* I've followed [this guide](https://cpp-pm-hunter.readthedocs.io/en/latest/creating-new/create/cmake.html)
* https://ci.appveyor.com/project/ned14/hunter-testing/builds/29630426
* https://travis-ci.org/ned14/hunter-testing/builds/626763837
* I have submitted CI configs to https://github.com/cpp-pm/hunter-testing targeting `pkg.template` branch,
see this merged pull request https://github.com/cpp-pm/hunter-testing/pull/24
* My change will resolve this "New package" request: https://github.com/cpp-pm/hunter/issues/91
=> zstd 1.4.5-d73e2fb-p0

cmake/configs/default.cmake, cmake/projects/Zug/hunter.cmake, docs/packages/pkg/Zug.rst, examples/Zug/CMakeLists.txt, examples/Zug/boo.cpp
* I've followed [this guide](https://cpp-pm-hunter.readthedocs.io/en/latest/creating-new/create/cmake.html)
* https://travis-ci.org/Bjoe/hunter/builds/627217052
* https://ci.appveyor.com/project/Bjoe/hunter-tdmm2/builds/29653805
* I have submitted CI configs to https://github.com/cpp-pm/hunter-testing targeting `pkg.template` branch,
see this merged pull request https://github.com/cpp-pm/hunter-testing/pull/25
=> Add 'Zug' package

cmake/projects/date/hunter.cmake
* https://ci.appveyor.com/project/kaihowl/hunter/builds/30044220
* Last config is broken. Checking what is wrong there.
* This is already broken without my changes. Proof: https://ci.appveyor.com/project/kaihowl/hunter/builds/30044401
* https://travis-ci.com/kaihowl/hunter/builds/143998584
=> Do not build tests in date library

cmake/configs/default.cmake, cmake/projects/PocoCpp/hunter.cmake, docs/packages/pkg/PocoCpp.rst
* https://travis-ci.org/Bjoe/hunter/builds/647456624
* https://ci.appveyor.com/project/Bjoe/hunter-t1t06/builds/30649578
* This update will change also some test toolchain
They are excluded/include in this pull request: https://github.com/cpp-pm/hunter-testing/pull/46
=> Update Pr.pococpp package

cmake/configs/default.cmake, cmake/projects/Protobuf/hunter.cmake
* https://ci.appveyor.com/project/hjmallon/hunter/builds/31176648
* https://travis-ci.org/hjmallon/hunter/builds/657232230
---
=> Update 'Protobuf' to v3.11.2-p0

examples/common.cmake
---
This reverts commit 7312c58361fc8e707eeea4de6c18c7d1b404d866.
Together with https://github.com/cpp-pm/hunter/pull/169 I can once again test locally with just cmake, no python or polly repo required
just go into the example directory and execute
```
cmake -S . -B _build
```
=> Revert "Remove git based support for testing examples"

docs/packages/database.rst
Updating the documentation to add sqlite to db section
=> Add sqlite3 to the database page

cmake/projects/Boost/hunter.cmake
Fixes #178 
Incorporates https://github.com/boostorg/build/issues/440
=> Update Boost to v1.72.0-p1

docs/packages/compression.rst, docs/packages/datetime.rst, docs/packages/networking.rst
=> Add asio, date and zstd to their respective package categories.

cmake/configs/default.cmake, cmake/projects/zstd/hunter.cmake
* https://ci.appveyor.com/project/hjmallon/hunter/builds/33056804
* https://travis-ci.org/github/hjmallon/hunter/builds/690106203
---
Thanks to @ned14 for sorting this all out before, this just pulls up to the released version.
=> Update 'zstd' to v1.4.5

docs/packages/pkg/GTest.rst
---
I noticed that the docs were a little out of date for GTest.
=> Improve docs for GTest

cmake/configs/default.cmake, cmake/projects/zlog/hunter.cmake, cmake/schemes/url_sha1_make_only.cmake.in, cmake/schemes/url_sha1_zlog.cmake.in, docs/packages/pkg/zlog.rst, examples/zlog/CMakeLists.txt, examples/zlog/boo.c
step by step carefully. **[Yes|No]**
Read all, several foolowed, not all.  I really wasn't interested on travis/appveyor accounts, but I did the travis one any ways.  I forked master, and worked on master, so didn't do the branching stuff.
Here is the links to the Travis/AppVeyor with status "All passed": 
* https://ci.appveyor.com/project/<username>/hunter/build/<n/a>?
* https://travis-ci.com/github/je-vv/hunter/builds/168680742
* I have submitted CI configs to https://github.com/cpp-pm/hunter-testing targeting `pkg.template` branch,
see this merged pull request https://github.com/cpp-pm/hunter-testing/pull/<number> …
=> Adding package zlog

.github/ISSUE_TEMPLATE/discussion.md
* I've checked this [Git style guide](https://0.readthedocs.io/en/latest/git.html). **[No]**
* I've checked this [CMake style guide](https://0.readthedocs.io/en/latest/cmake.html). **[No]**
---
When starting a discussion I learned that there is a gitter but the link is broken. I updated the link, see u in gitter ;)
=> updated the gitter link in the issue-template for discussions

cmake/configs/default.cmake, cmake/projects/re2/hunter.cmake, examples/re2/CMakeLists.txt
* https://ci.appveyor.com/project/rbsheth/hunter/builds/34646819
* https://travis-ci.com/github/rbsheth/hunter/builds/179648936
=> Update 're2' to v2020.08.01

cmake/configs/default.cmake, cmake/projects/Protobuf/hunter.cmake
* https://ci.appveyor.com/project/rbsheth/hunter/builds/34648835
* https://travis-ci.com/github/rbsheth/hunter/builds/179665275
=> Update 'Protobuf' to v3.12.4-p1

cmake/configs/default.cmake, cmake/projects/spdlog/hunter.cmake
* https://ci.appveyor.com/project/craffael/hunter/builds/35390953
* https://travis-ci.org/github/craffael/hunter/builds/730044314
---
=> Update spdlog to 1.8.0

cmake/configs/default.cmake, cmake/projects/jpeg-compressor/hunter.cmake, docs/packages/pkg/jpeg-compressor.rst, examples/jpeg-compressor/CMakeLists.txt, examples/jpeg-compressor/boo.cpp
=> Add 'jpeg-compressor' package

docs/packages/pkg/apg.rst, docs/packages/pkg/jpeg-compressor.rst
Should probably automate this too...
=> Update PR numbers

cmake/configs/default.cmake, cmake/projects/jsmn/hunter.cmake, docs/packages/pkg/jsmn.rst, examples/jsmn/CMakeLists.txt, examples/jsmn/boo.cpp
=> Add 'jsmn' package

cmake/configs/default.cmake, cmake/projects/KhronosDataFormat/hunter.cmake, docs/packages/pkg/KhronosDataFormat.rst, examples/KhronosDataFormat/CMakeLists.txt, examples/KhronosDataFormat/boo.cpp
=> Add 'KhronosDataFormat' package

cmake/configs/default.cmake, cmake/projects/KhronosDataFormat/hunter.cmake
=> Update 'KhronosDataFormat' to v1.3.1-1f8c852-p1

cmake/configs/default.cmake, cmake/projects/spirv-cross/hunter.cmake
=> Update spirv-cross to 20200917

cmake/configs/default.cmake, cmake/projects/abseil/hunter.cmake
=> Update abseil to 20200923.2

cmake/configs/default.cmake, cmake/projects/Protobuf/hunter.cmake
=> Update Protobuf to v3.14.0-4a09d77-p0

cmake/configs/default.cmake, cmake/projects/Boost/hunter.cmake
=> Boost 1.75.0 without mingw update

cmake/configs/default.cmake, cmake/projects/zstd/hunter.cmake
=> Update 'zstd' to v1.4.8

cmake/configs/default.cmake, cmake/projects/KhronosDataFormat/hunter.cmake
=> Update KhronosDataFormat to 1.3.1-1f8c852-p2

cmake/projects/opusfile/hunter.cmake, examples/opusfile/CMakeLists.txt
Alter 'opusfile' package to disable opusurl build by default.
(opusurl has OpenSSL as dependency, this  leads to enormous test/build times)
---
=> Alter 'opusfile' package, disable opusurl build

cmake/configs/default.cmake, cmake/projects/KhronosDataFormat/hunter.cmake, examples/KhronosDataFormat/boo.cpp
=> Update KhronosDataFormat to v1.3.1-1f8c852-p3

cmake/configs/default.cmake, cmake/projects/KTX-Software/hunter.cmake, docs/packages/pkg/KTX-Software.rst, examples/KTX-Software/CMakeLists.txt, examples/KTX-Software/boo.cpp
=> Add package KTX-Software

cmake/configs/default.cmake, cmake/projects/zstd/hunter.cmake
=> Update zstd to v1.5.0.

cmake/configs/default.cmake, cmake/projects/spdlog/hunter.cmake
* I've followed [this guide](https://hunter.readthedocs.io/en/latest/creating-new/update.html) step by step carefully. **[Yes]**
fixes #518
=> Update spdlog to version 1.9.2

cmake/configs/default.cmake, cmake/projects/jwt-cpp/hunter.cmake, examples/jwt-cpp/main.cpp
***
The original tag that was used to add jwt-cpp was purely for testing, I would like to delete it from GitHub as to not confuse users 😄 which is why I replaced the old version.
=> Update jwt-cpp to latest release

cmake/configs/default.cmake, cmake/projects/abseil/hunter.cmake
=> Update abseil to v20211102.0

cmake/configs/default.cmake, cmake/projects/Protobuf/hunter.cmake
=> Update Protobuf to v3.19.4-p0

cmake/configs/default.cmake, cmake/projects/Catch/hunter.cmake
=> Update 'Catch' to add versions 2.11.3, 2.12.4, 2.13.9

cmake/configs/default.cmake, cmake/projects/re2/hunter.cmake
=> Update re2 to 2022.04.01

docs/creating-new/test.rst
I'm sorry!
* I've checked this [CMake style guide](https://0.readthedocs.io/en/latest/cmake.html). **[No]**
---
=> Fix typo in docs

cmake/configs/default.cmake, cmake/projects/GTest/hunter.cmake
=> Update 'GTest' package to v1.12.1

cmake/configs/default.cmake, cmake/projects/abseil/hunter.cmake
=> Update abseil to LTFS 20220623.1

cmake/configs/default.cmake, cmake/projects/spdlog/hunter.cmake
Relates to https://github.com/cpp-pm/spdlog/pull/3
=> Update spdlog package to 1.12.0-p0

cmake/configs/default.cmake, cmake/projects/GTest/hunter.cmake
=> Update 'GTest' to v1.14.0

cmake/configs/default.cmake, cmake/projects/abseil/hunter.cmake
=> Update 'abseil' to 20230802.1

cmake/configs/default.cmake, cmake/projects/sqlite3/hunter.cmake
Requires merge and tag of https://github.com/cpp-pm/sqlite3/pull/2 before it can be updated / merged
=> Update 'sqlite3' to v3.43.2

cmake/configs/default.cmake, cmake/projects/ceres-solver/hunter.cmake
Fix that SuiteSparse built with Hunter is always built with Partition support.
=> ceres-solver: update to v2.2.0-p1

cmake/configs/default.cmake, cmake/projects/Alut/hunter.cmake, docs/packages/pkg/Alut.rst, examples/Alut/CMakeLists.txt, examples/Alut/main.cpp
---
needs a fork of https://github.com/vancegroup/freealut in cpp-pm org
=> Add 'Alut' package

docs/quick-start/boost-components.rst
* My change will resolve this request: https://github.com/cpp-pm/hunter/issues/546
---
=> docs: update URL to tar file for boost-components documentation

.github/workflows/set_matrix.py
Fix some typos in output, variable-names and comments.
The usage of `[\d]` in regex is explicit, but also uneccessarily complex. Simplify a bit.
=> set_matrix: simplify regex, fix typos
