cmake/configs/default.cmake
cmake/projects/Boost/hunter.cmake

step by step carefully. **YES**
* I've tested this package remotely and have excluded all broken builds. **NO**
Here is the links to the Travis/AppVeyor with:
* https://travis-ci.org/dan-42/hunter/builds/598490205
* https://ci.appveyor.com/project/dan-42/hunter/builds/28140957
* The boost package https://github.com/cpp-pm/boost/tree/hunter-1.71.0 was created by using the following script https://gist.github.com/dan-42/ef7ac7306dcde31efa97d66a227baf3e

update Boost to 1.71.0

---

cmake/modules/hunter_download_server_url.cmake

* My change will work with CMake 3.2 (minimum requirement for Hunter). **[Yes**]
Currently when using HUNTER_DOWNLOAD_SERVER it spams a quite a lot. With this pull request those messages are only shown if HUNTER_STATUS_DEBUG is enabled

Hide HUNTER_DOWNLOAD_SERVER messages

---

docs/packages/pkg/zip.rst

I noticed a broken link browsing the documentation.
* I've checked this [CMake style guide](https://0.readthedocs.io/en/latest/cmake.html). **[No]**
---

Fixed broken link in zip.rst

---

cmake/projects/ZLIB/hunter.cmake

Upstream commit from https://github.com/ruslo/hunter
I modified this to be a non-default version of the ZLIB package, since it should be a drop in replacement but users may not want this version and adding both `zlib` and `chromium_zlib` may cause conflicts.

Add chromium_zlib package as ZLIB

---

cmake/projects/Jpeg/hunter.cmake

Adding experimental functionality to see if `turbojpeg` can replace `libjpeg` in existing dependencies. Avoiding making `turbojpeg` the default option.
Something to note is that `turbojpeg` will generate machine code that may not be portable (ex. with AVX2) but Hunter will still cache and distribute the binaries to similar machines. Perhaps we need to add an architecture flag to the toolchain or the package name.

Add libjpeg-turbo as jpeg

---

cmake/projects/yaml-cpp/hunter.cmake

Fixes the SHA1 for "0.6.2-0f9a586-p1" to be lower-case.
FYI @cristianadam @Ba777

Fix yaml-cpp SHA1

---

cmake/projects/ZLIB/hunter.cmake

Avoid looking for `pkgconfig` file when building `chromium_zlib` as `ZLIB` and make sure to export `ALIAS` target `ZLIB::zlib` for older packages.

Update ZLIB configuration and version for chromium_zlib drop-in

---

cmake/schemes/url_sha1_download.cmake.in

HUNTER_DOWNLOAD_SERVER replaces the single download URL with multiple
ones to be tried.
The download scheme uses file(DOWNLOAD), which does not support a list
of ULRs. When used together this causes an error
As a side effect of this commit the download scheme now supports
HUNTER_PACKAGE_PROTECTED_SOURCES.
fixes: https://github.com/cpp-pm/hunter/issues/79

fix download scheme with HUNTER_DOWNLOAD_SERVER

---

cmake/modules/hunter_download.cmake
cmake/modules/hunter_final_config.cmake
cmake/modules/hunter_get_source_subdir.cmake
cmake/modules/hunter_source_subdir.cmake
cmake/schemes/url_sha1_cmake.cmake.in
docs/reference/user-modules/hunter_source_subdir.rst

fixes https://github.com/cpp-pm/hunter/issues/94

Add SOURCE_SUBDIR for cmake scheme

---

cmake/configs/default.cmake
cmake/projects/Boost/hunter.cmake
examples/Boost-system/CMakeLists.txt

* I've followed [this guide](https://cpp-pm-hunter.readthedocs.io/en/latest/creating-new/update.html)
* https://travis-ci.org/dan-42/hunter/builds/631285299
* https://ci.appveyor.com/project/dan-42/hunter/builds/29828770

Update Boost 1.72.0-p0

---

cmake/projects/hunter_venv/hunter.cmake

* Travis make no guarantees for Python version
stability on their images for macOS.
The version numbers in this file are meant to match those on the CI system. However, the macOS xcode9.4 image on Travis now has 3.7.5.
Here is a Travis run of the failing `pkg.pip_numpy` branch with this change on top showing macOS build success:
* https://travis-ci.org/hjmallon/hunter/builds/632249789

Update CI Python versions where they have updated upstream

---

cmake/schemes/url_sha1_pip.cmake.in

After testing my PR (https://github.com/cpp-pm/hunter/pull/117) which is intended to fix https://github.com/cpp-pm/hunter/issues/115 I updated the `pip_numpy` test branch by merging `pkg.template`. This caused another failure in MSVC builds.
It seems the verbose option added to pip here https://github.com/cpp-pm/hunter/commit/9d7af40041326b7eeefc28a30536bb19dada742d can confuse MSVC if the output of the …

Fix pip builds with up to date pkg.template

---

cmake/projects/opentracing-cpp/hunter.cmake

Same like this PR https://github.com/cpp-pm/hunter/pull/73
The SHA check failed on CentOS env... error log 
```
...
-- verifying file...
file='/root/.hunter/_Base/Download/opentracing-cpp/1.6.0/F5DCCF2/v1.6.0.tar.gz'
-- SHA1 hash of
/root/.hunter/_Base/Download/opentracing-cpp/1.6.0/F5DCCF2/v1.6.0.tar.gz
does not match expected value
expected: 'F5DCCF21DC05CDDB6205164A8FD3CF210926EF6C'
actual: 'f5dccf21dc05cddb6205164a8fd3cf210926ef6c'
-- Hash mismatch, removing...
-- Retry after 60 seconds (attempt #5) ...
-- downloading...
src='https://github.com/opentracing/opentracing-cpp/archive/v1.6.0.tar.gz'
dst='/root/.hunter/_Base/Download/opentracing-cpp/1.6.0/F5DCCF2/v1.6.0.tar.gz'
timeout='none'
-- verifying file...
file='/root/.hunter/_Base/Download/opentracing-cpp/1.6.0/F5DCCF2/v1.6.0.tar.gz' …
```

opentracing-cpp 1.6.0 SHA1 change to lowercase

---

cmake/configs/default.cmake
cmake/projects/spdlog/hunter.cmake

* I've followed [this guide](https://cpp-pm-hunter.readthedocs.io/en/latest/creating-new/update.html)
* https://ci.appveyor.com/project/dan-42/hunter/builds/29827625
* https://travis-ci.org/dan-42/hunter/builds/631261840
the **-p2**  means that I use the latest changes from spdlogs branch  `` v1.x `` which includes a fix when compiling on gcc9.2 which misses an **#include <cassert>**
Please delete the following branch `` hunter-1.4.2-p1 ``  from the repo **https://github.com/cpp-pm/spdlog**  as I created it accidently from spdlog's  `` master ``-branch which is wrong.
And I do not have the privileges to delete a …

Update spdlog to 1.4.2-p2, fixing missing cassert include

---

cmake/projects/Boost/schemes/url_sha1_boost_library.cmake.in
docs/packages/pkg/Boost.rst
examples/Boost-python-numpy/CMakeLists.txt
examples/Boost-python-numpy/config.cmake
examples/Boost-python-numpy/foo.cpp

* Use CMAKE option HUNTER_ENABLE_BOOST_PYTHON_NUMPY to enable
---
This change adds a CMAKE option to Boost install to allow build and install of the boost-python-numpy plugin, which is part of boost-python since around boost 1.63. The change is currently labelled WIP as I would like feedback on the docs and flag names etc and the builds are running. I have included and example and added that to the testing matrix for boost in a PR here (https://github.com/cpp-pm/hunter-testing/pull/27).
---
* I've followed [this guide](https://cpp-pm-hunter.readthedocs.io/en/latest/creating-new/update.html)
* …

Boost Python: Add optional numpy support

---

cmake/projects/glbinding/hunter.cmake

* https://ci.appveyor.com/project/caseymcc/hunter/builds/30675491
* https://travis-ci.org/caseymcc/hunter/builds/648051318
* This update will break few old toolchains.
They are excluded in this pull request: https://github.com/cpp-pm/hunter-testing/pull/47

(Ready) - Fix sha1 for latest glbinding, current is sha1 to updater's archive 

---

docs/old-wiki/Requirements.md
docs/old-wiki/dev.hunter.root.md
docs/old-wiki/example.custom.config.id.md
docs/overview/customization/config-id.rst
docs/packages/pkg/OpenCV.rst
docs/quick-start.rst
docs/quick-start/boost-components.rst
docs/reference/user-variables.rst
docs/user-guides/hunter-developer/cmake-launch.rst

* Find/Replace in docs/ of:
* https://github.com/hunter-packages/gate
* https://raw.githubusercontent.com/cpp-pm/gate
There are loads more `gate` links in the examples, but it made for a noisy change to include them (~500 extra lines changed).

Update HunterGate links to cpp-pm

---

cmake/modules/hunter_make_directory.cmake

This commit fixes the issue that SHA1 may not match due to different case sensitivity. For example, the `yaml-cpp` package is currently broken because of this reason.
[hunter ** INTERNAL **] Short SHA1 collision:
[hunter ** INTERNAL **]   956C2B5FBF5AA0EB8EF5EF890C0328B3AA357A13 (from /Users/usrname/.hunter/_Base/Download/yaml-cpp/0.6.2-0f9a586-p1/956c2b5/SHA1)
[hunter ** INTERNAL **] …

Compares SHA1 strings in case insensitive.

---

.gitignore

ignore more build folder, originally only `_builds` folder, but I have `_build` folders for local testing. Now both are supported
Working with VSCode one can add the python plugin and a rst plugin to locally create the documentation. The default python virtual environment folder name in Visual Studio is `env`, so I added it

Ignore more build folder and python venv folder

---

cmake/projects/OpenSSL/schemes/url_sha1_openssl_windows.cmake.in
cmake/projects/OpenSSL/schemes/url_sha1_openssl_windows_1_1_plus.cmake.in

This adds a config option that works like the ASM_SUPPORT option to enable building openssl with debug runtime (e.g. `/MTd` switch).  The openssl build just needs a 'debug-' prefix on the arch name.  Usage in your config.cmake:
```
hunter_config(OpenSSL VERSION ${HUNTER_OpenSSL_VERSION}
CMAKE_ARGS DEBUG_RUNTIME=ON
)
```

support debug runtime build of openssl on windows

---

cmake/configs/default.cmake

This commit updates Boost’s default version to 1.72.0-p1 to take advantage of the #180 fix.

Updates Boost’s default version to 1.72.0-p1.

---

cmake/configs/default.cmake
cmake/projects/abseil/hunter.cmake
docs/packages/pkg/abseil.rst
examples/abseil/CMakeLists.txt
examples/abseil/boo.cpp

* https://ci.appveyor.com/project/rbsheth/hunter/builds/34648951
* https://travis-ci.com/github/rbsheth/hunter/builds/179666064
* I have submitted CI configs to https://github.com/cpp-pm/hunter-testing targeting `pkg.template` branch,
see this merged pull request https://github.com/cpp-pm/hunter-testing/pull/68

Add 'abseil' package

---

cmake/modules/hunter_setup_msvc.cmake

* My change will work with CMake 3.2 (minimum requirement for Hunter). **[Yes|No]**
---
This is the first and most important part of https://github.com/cpp-pm/hunter/pull/258 and is useful independantly as it should mean many projects with common build systems will work.

Add basic support for MSVC ARM64

---

.github/workflows/set_matrix.py

The matrix override files are in JSON format. Add the possibility to uncomment
build toolchains and add information why the toolchain was removed instead of
just deleting the toolchain in the files.

Allow // comments in matrix.json for CI

---

cmake/projects/libarchive/hunter.cmake
examples/libarchive/boo.cpp
scripts/pkgconfig-export-targets.cmake.in

This change adds missing compressor dependencies for libarchive.
I needed to change "pkgconfig-export-targets.cmake.in" since it was creating invalid dependencies.  It seems like it's the correct change to make here.  I'm not completely sure it won't break other things, though.  Is there a way to run the CI builds on everything?
---

[libarchive] add dependencies on compressor libraries

---

cmake/projects/OpenSSL/schemes/url_sha1_openssl_ios.cmake.in

The iOS target names has been changed for a long time and `-sysroot` is required to avoid build errors.
step by step carefully. **[Yes|No]**
* My change will resolve this "New package" request: https://github.com/cpp-pm/hunter/issues/<number>
---
---
* I will try to keep this pull request as small as …

Fix iOS build for OpenSSL.

---

docs/packages/pkg/Boost.rst

I've just fixed a broken link in the docs. I've clicked the new link once in the preview, but no further tests done. ;-)

Fix example project link

---

cmake/projects/OpenSSL/schemes/url_sha1_openssl_ios.cmake.in

iOS bitcode toolchain includes following architectures: armv7, arm64, i386, x86_64. armv7 and i386 are not handled in the scheme, so build fails. Fixed it.
---

fixed openssl build for ios

---

cmake/projects/Boost/hunter.cmake

Yesterday there was a scheduled downtime of Bintray and there will be one on the 26th of April as well.
For more details:
* https://github.com/boostorg/boost/issues/502
* https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

Update boost base url to fix bintray deprecation

---

scripts/create-toolchain-info.cmake

* Setting CMAKE_OSX_ARCHITECTURES to "arm64;x86_64" can cause output
in either order so predefined macros must be alphanumerically
sorted before putting into toolchain file.
---
Fixes https://github.com/cpp-pm/hunter/issues/382. This will cause new Toolchain-IDs for all users who update Hunter versions past this PR.

Fix Apple Toolchain-ID changing on reconfigure

---

cmake/configs/default.cmake
cmake/projects/Boost/generate.sh
cmake/projects/Boost/hunter.cmake
cmake/projects/Boost/nowide/hunter.cmake
cmake/projects/Boost/type_erasure/hunter.cmake

---
It might be nice to remove the `hunter_default_version` hack in `default.cmake`, but someone interested in MINGW would need to look at that.

Update Boost to 1.76.0

---

cmake/configs/default.cmake
cmake/projects/GTest/hunter.cmake

This updates GTest to Version 1.11.0 which, most notably, also successfully compiles with Gcc-11 :)

add gtest version 1.11.0

---

scripts/find_python.cmake

For CMake >= 3.15 wrong version of Python is found in the find_python.cmake script
this leads to error in ci testing on cache upload as 'requests' module is not found
https://github.com/cpp-pm/hunter/runs/2738382465#step:7:4079
see: https://cmake.org/cmake/help/v3.15/policy/CMP0094.html#policy:CMP0094
---

fix find_python script for cmake >= 3.15

---

cmake/modules/hunter_pack_git_submodule.cmake

---
Finally got round to fixing this issue: https://github.com/cpp-pm/hunter/issues/395

Fix GIT_SUBMODULE mode for nested submodule (fixes #395)

---

.github/workflows/ci/build.cmd
.github/workflows/ci/build.sh

Helps to mitigate problem with manual workflow run in forked repo (as it's done on the master branch).
Without this change manual package test result in error:
[hunter ** FATAL ERROR **] Upload: PASSWORD is missing
---

don't upload cache if password is not set

---

cmake/configs/default.cmake
cmake/projects/Boost/hunter.cmake

* I've followed [this guide](https://hunter.readthedocs.io/en/latest/creating-new/update.html) step by step carefully. **Yes**
upstream release page: https://www.boost.org/users/history/version_1_77_0.html

Update Boost to v1.77.0

---

cmake/configs/default.cmake
cmake/projects/abseil/hunter.cmake

[CI build](https://github.com/tgval/hunter/actions/runs/1233508042) - See all toolchains pass, except for `analyze-cxx17` on ubuntu 20.04. I've looked at previous release [test](https://github.com/cpp-pm/hunter/pull/317/checks?check_run_id=1511635180) which seems to indicate the analyze toolchain was also not successful.

Update abseil to 20210324.2

---

cmake/configs/default.cmake
cmake/projects/Boost/hunter.cmake

step by step carefully. [Yes]
I will remove these lines if nothing breaks.
* This update will break a few toolchains.
- Toolchain 1
- Toolchain 2

Update 'boost' to v1.78.0

---

scripts/find_python.cmake
scripts/link-all.cmake

* I've checked this [Git style guide](https://0.readthedocs.io/en/latest/git.html). **[No]**
---
Closes: https://github.com/cpp-pm/hunter/issues/367
As stated in the issue, the change https://github.com/cpp-pm/hunter/commit/f43d5f3e2ecf7e0094f4b25f85ffb221788f582d bumped required CMake version to `3.12`. This reverts it by using previous behavior for version less than `3.12` and new behavior otherwise. 
(PR just combines the removed and added bits from the …

Reduced required CMake version

---

.github/workflows/ci/build.cmd

This fixes a bug in #454 due to which no tests were really run on Windows on any branch other than master

fix Win ci not running on any branch except master

---

docs/packages/pkg/Boost.rst

---
document a flag that can be used on Windows builds of Boost libraries to link the libraries against the static runtime libraries.

docs: Boost: mention BOOST_BUILD_DYNAMIC_VSRUNTIME

---

examples/szip/CMakeLists.txt
examples/szip/foo.cpp

szlib is compiled as a pure C static library. So there is no C++
name-mangling done. When including the `szlib.h` header into a C++
project the compiler assumes the header to be a C++ header and does
name-mangling. This results in linker errors when using szip-functions.
The second problem is the usage of `size_t` inside `szlib.h` whithout a
`stddef.h` include. Probably some other include provided the `size_t` in
the past, but maybe the stdlib changed and this missing include is
surfacing now.

szip: Fix example compile with size_t and extern "C"

---

cmake/projects/CLI11/hunter.cmake

The args were changed in 1.9.0 so update the args
leave the old args for backwards compatibility

Update CLI11 default args

---

cmake/projects/OpenSSL/schemes/url_sha1_openssl_macos.cmake.in

The MacOS scheme for OpenSSL defaults to "x86_64" if CMAKE_OSX_ARCHITECTURES is not set. This can result in a broken build on M1 (arm64) Macs if the CMake configuration depends on OpenSSL via Hunter. This pull request replaces the "x86_64" default with CMAKE_SYSTEM_PROCESSOR.

More intelligent build arch default in macos scheme for OpenSSL

---

docs/requirements.txt

This pr fixes issue https://github.com/cpp-pm/hunter/issues/555
Further reading https://github.com/readthedocs/readthedocs.org/issues/9037

ci-docs fix #555 by adding jinja2 package to dependencies

---

docs/packages/pkg/asio-grpc.rst

Quote asio and grpc mentions for spellchecking and add the words `asio` and `grpc` separately to make spellchecking for `asio-grpc` happy.
Fixes: https://github.com/cpp-pm/hunter/issues/569

docs: fix asio-grpc package documentation build

---

docs/packages/pkg/fmt.rst

On Ubuntu 22.04 jammy with Sphinx 4.3.0 and spell checker 7.2.1 the word `formatter` in the `fmt.rst` package documentation is flagged as an spelling mistake.
Explicitly add the word to silence the warning.

docs: fmt: add formatter to fix spelling error

---

cmake/projects/OpenSSL/schemes/url_sha1_openssl.cmake.in

step by step carefully. **[Yes|No]**
* My change will allow compile OPENSSL with [emscripten-cxx14.cmake](https://github.com/ruslo/polly/blob/master/emscripten-cxx14.cmake)
---
step by step carefully. **[Yes}**
---
* I've checked this [Git style guide](https://0.readthedocs.io/en/latest/git.html). **[Yes}**
* I've checked this [CMake style guide](https://0.readthedocs.io/en/latest/cmake.html). **[Yes}**
* My change will work with CMake 3.2 (minimum requirement for Hunter). **[Yes|No]**
* I will try to keep this pull request as small as possible and will try not to mix unrelated features. …

add command and options to compile with emscripten

---

cmake/schemes/git_tag_cmake.cmake.in
cmake/schemes/url_sha1_cmake.cmake.in

* According to https://gitlab.kitware.com/cmake/cmake/-/issues/21282
* Use cmake --install . rather than --build . --target install to avoid database is locked error.
---

Fix CMAKE_IOS_INSTALL_COMBINED on Xcode 12+

---

cmake/configs/default.cmake
cmake/projects/Boost/hunter.cmake

Update Boost package to v1.79.0.
Release notes: https://www.boost.org/users/history/version_1_79_0.html

Boost: update to v1.79.0

---

cmake/configs/default.cmake
cmake/projects/Boost/hunter.cmake

I used the 7z instead of the tar.bz2 because it almost 20MB smaller and cmake supports it as well.

add boost 1.80.0

---

cmake/projects/aws-sdk-cpp/hunter.cmake

* I've checked this [Git style guide](https://0.readthedocs.io/en/latest/git.html). **[Yes|]**
---
Sorry @NeroBurner I should have labelled the other MR as 'do not merge until the upstream MR is merged and I have updated the links'. 😄

aws-sdk-cpp: Fix link pointing to wrong fork

---

cmake/projects/OpenBLAS/hunter.cmake
docs/packages/pkg/OpenBLAS.rst

Starting with OpenBLAS 0.3.21 a f2c-converted copy of LAPACK 3.9.0 is available as fallback when "no fortran compiler" is specified. This means we get full BLAS/LAPACK support with just a normal C++ compiler.
From the release notes: https://github.com/xianyi/OpenBLAS/releases/tag/v0.3.21
> - when no Fortran compiler is available, OpenBLAS builds will now automatically
>   build LAPACK from an f2c-converted copy of LAPACK 3.9.0 unless the NO_LAPACK option
>   is specified (more recent releases make too heavy use of Fortran90+ features to be easily convertible to C)
Also disable the building of tests when building for Hunter to save time

OpenBLAS: starting with 0.3.21 build with LAPACK support per default

---

index.md

Generate for each project an anchor (table id) and add the link to each project name. This can be used to link to a status of a specific project.
for example I can link to the `Boost` project table as follows: https://neroburner.github.io/hunter/#Eigen
For presentation purposes I've let the gh-pages be created on my fork (see link above)

pages: add id anchor per project for direct link

---

cmake/configs/default.cmake
cmake/modules/hunter_get_boost_libs.cmake
cmake/projects/Boost/ci/matrix.json
cmake/projects/Boost/hunter.cmake
cmake/projects/Boost/url/hunter.cmake
examples/Boost-url/CMakeLists.txt
examples/Boost-url/foo.cpp

Update boost to v1.81.0

---

cmake/modules/hunter_dump_cmake_flags.cmake
cmake/modules/hunter_pick_scheme.cmake
cmake/projects/Boost/schemes/url_sha1_boost_ios_library.cmake.in

---
Fixes Boost libraries (i.e. not the header only bit which was already fine) on iOS simulator only. hunter_pick_scheme was not choosing iOS schemes for `iphonesimulator` `CMAKE_OSX_SYSROOT`s before. Also the download step was being skipped as it was assuming that ios and simulator were being built together.
See https://github.com/cpp-pm/hunter/issues/588

Boost: Add support for iOS simulator-only builds

---

cmake/projects/ceres-solver/hunter.cmake

The latest ceres-solver `v2.1.0-p1` version tries to build against CUDA, introducing an unwanted runtime dependency.
The user should explicitly choose to build against system CUDA libraries (or provided by hunter).
Fixes: https://github.com/cpp-pm/hunter/issues/657

ceres-solver: per default disable CUDA support

---

cmake/modules/hunter_sanity_checks.cmake

fix for 'Ninja Multi-Config' generator

---

.github/workflows/ci.yml
.github/workflows/ci/build_hunter_tests.sh
.github/workflows/ci/matrix_hunter_tests.json
.github/workflows/set_matrix.py
cmake/modules/hunter_setup_msvc.cmake
tests/hunter_setup_msvc/CMakeLists.txt

`HUNTER_MSVC_ARCH` should match the capitalization of the `vcvarsall.bat <arch>` argument. The arch argument according to `vcvarsall.bat /help` can be one of the following:
```
[arch]: x86 | amd64 | x86_amd64 | x86_arm | x86_arm64 | amd64_x86 | amd64_arm | amd64_arm64
```
But to be more like `vcvarsall.at` and `cmake -A`, be case-insensitive with the input architectures.
And for less confusion, always output the `HUNTER_ARCH` variables in lower case.
In the process cleanup, fix and extend the corresponding unittest.
Fixes: https://github.com/cpp-pm/hunter/issues/679

hunter_setup_msvc: tolower to fix arm64 vs ARM64 confusion

---

cmake/configs/default.cmake
cmake/projects/zstd/hunter.cmake

Add zstd versions 1.5.1, 1.5.2, 1.5.4, and 1.5.5 .
New default v1.5.5 has been tested locally.

Update zstd package to 1.5.5

---

cmake/configs/default.cmake
cmake/projects/ceres-solver/hunter.cmake
examples/ceres-solver-suitesparse-dynLAPACK/config.cmake
examples/ceres-solver-suitesparse/CMakeLists.txt
examples/ceres-solver-suitesparse/config.cmake

Update examples using SuiteSparse, building with OpenBLAS per default, ant one testing with dynamic-LAPACK package.
On older GCC versions like 7.5 from Ubuntu 18.04 bionic fall back to older ceres-solver `2.1.0-p1` version, as `2.2.0` needs a fully C++17 compliant compiler.
- Ubuntu 18.04 disablement: https://github.com/ceres-solver/ceres-solver/commit/40c1a7e18ee040261f87b32374c9a46724ca2214
- C++17 requirement: https://github.com/ceres-solver/ceres-solver/commit/1274743609bc59621adc9e311cdeeaad7eb65201
Fix the `CUDA=OFF` option, as it was renamed to `USE_CUDA`. Still disable both.

ceres-solver: update to v2.2.0-p0 and fix examples

---

cmake/projects/Eigen/hunter.cmake

We don't want different packages be created wheter a Fortran compiler is available or not. As Eigen 3.4.0 has no flags to disable the Fortran related code hook into the
[CheckLanguge](https://cmake.org/cmake/help/latest/module/CheckLanguage.html) CMake feature.
For the variable `CMAKE_<LANG>_COMPILER` the documentation states the following:
> If this variable is already set, either explicitly or cached by a previous
> call, the check is skipped.
We use this to effectively force Eigen to think that there was no Fortan compiler.
Fixes the ninja and nmake vs-16-2019 based toolchains.

Eigen: explicitly disable Fortran usage

---

cmake/configs/default.cmake
cmake/projects/Boost/hunter.cmake

---
* The first commit reorders the hunter.cmake file into version order and does not contain any functional changes
* There appear to be no new build-required parts of Boost in 1.82 or 1.83.
* Sorry for removing the 7z files, but they require us to set LC_* env vars all over our CI (I can send another version without this part of the change if you would rather).

Update 'Boost' to 1.83

---

cmake/configs/default.cmake
cmake/projects/re2/hunter.cmake

Includes versions: 2022.06.01, 2022.12.01, 2023.02.01, 2023.03.01
More recent versions introduce a dependency on Google Abseil, so will require a fork.
Tested locally on macOS 13.6 with Apple clang 15.0.0 .

Update 're2' to v2023.03.01

---

docs/creating-new/create/cmake.rst

This commit improves the documentation of the prcess for adding new packages. It replaces two shell commands for SHA1 calculation with one using a pipe. This allows you not to delete the downloaded archive from the file system later.
The commit also corrects the SHA1 sums shown in the example.
* I've checked this [CMake style guide](https://0.readthedocs.io/en/latest/cmake.html). **[No]**
* My change will work with CMake 3.5 (minimum requirement for Hunter). **[Yes]**
---

docs: Add SHA1 calculation onliner and fix sums

---

cmake/configs/default.cmake
cmake/projects/ceres-solver/hunter.cmake

Support the latest `SuiteSparse-metis-for-windows` `v7.5.1-1` release, which doesn't provide the `SuiteSparse::metis` target anymore, as Metis is now a private dependency of the SuiteSparse cholmod module.
Also disable `EIGENMETIS` build option as it needs Metis.

ceres-solver: update to 2.2.0-p2 with SuiteSparse v7.5.1-1 support

---

.github/workflows/ci-docs.yml
.github/workflows/ci.yml
.github/workflows/ci/build.cmd

* My change will work with CMake 3.5 (minimum requirement for Hunter). **Yes**
---
* CI update depricated packages and routines
* CI fix MinGW build, closes #709

CI updates and fixes

---

cmake/modules/hunter_setup_msvc.cmake

Visual Studio 2022 versions have rolled over from 1930s to 1940s with the release of 17.10
https://learn.microsoft.com/en-us/cpp/overview/compiler-versions

Add support for Visual Studio 2022 version 17.10

---

cmake/configs/default.cmake
cmake/projects/Boost/hunter.cmake
cmake/projects/GTest/hunter.cmake

upgrade gtest to 1.15.2

---

cmake/configs/default.cmake
cmake/projects/abseil/hunter.cmake

* This update will break a few toolchains.
- gcc-7-cxx17 ubuntu-20.04
- mingw-cxx17 windows-2019
- msys-cxx17 windows-2019

Update 'abseil' to 20240116.2

---

cmake/projects/Boost/hunter.cmake

* My change will work with CMake 3.5 (minimum requirement for Hunter). **[Yes]**
---
Fix for https://github.com/cpp-pm/hunter/issues/770.
The change will affect https://github.com/cpp-pm/hunter/pull/759 (URL will need to be changed).
SHA1 has not changed.
<details>
<summary>SHA1 for changed URLs</summary>
```
https://archives.boost.io/release/1.65.0/source/boost_1_65_0.tar.bz2  f9260074ecfb31f3e65322fae9c15cc423c0ad59
https://archives.boost.io/release/1.65.1/source/boost_1_65_1.tar.bz2 …
```

Replaced boostorg.jfrog.io to archives.boost.io URLs

---

cmake/modules/hunter_get_lang_standard_flag.cmake

* My change will work with CMake 3.10 (minimum requirement for Hunter). **Yes**
Update the checks language checks for C++23, C++26, C17 and C23
fixes #756

Update language checks for CXX and C

---

docs/creating-new/create/cmake.rst

* I will try to keep this pull request as small as possible and will try not to mix unrelated features. **Yes*
As @NeroBurner pointed out in https://github.com/cpp-pm/hunter/pull/600 one should update the copyright notices when a new package is created. This PR points this out to the user in the guide to create a new package.

Add note about updating copyright notes to the manual

---

scripts/link-all.py

Code changes by  @aggiehorns
When we have more CPUs than files to link the `files_per_job` variable got `0`. And then the begin and end indexes got wrong and multiple jobs tried to link the same file.
Fixes: https://github.com/cpp-pm/hunter/issues/664

fix link-all.py with high CPU count and little files

---

cmake/projects/OpenBLAS/hunter.cmake

The OpenBLAS build has uncountable many warnings. Disable them as we don't need them. Only errors are really interesting.

OpenBLAS: silence warnings
